function numByKc(kc){
  switch(kc) {
    case 65:
      return 42;
    case 73:
      return 36;
    case 85:
      return 35;
    case 69:
      return 31;
    case 79:
      return 37;
    case 75:
      return 49;
    case 83:
      return 43;
    case 84:
      return 33;
    case 78:
      return 60;
    case 72:
      return 47;
    case 77:
      return 61;
    case 89:
      return 34;
    case 82:
      return 32;
    case 87:
      return 30;
    case 71:
      return 46;
    case 90:
      return 55;
    case 74:
      return 48;
    case 68:
      return 44;
    case 66:
      return 59;
    case 86:
      return 58;
    case 80:
      return 38;
    case 70:
      return 45;
    case 81:
      return 29;
    case 76:
      return 50;
    case 88:
      return 56;
    case 67:
      return 57;
    default:
      return 0;
    }
}

function charByKc(kc){
  switch(kc) {
    case 65:
      return "A";
    case 73:
      return "I";
    case 85:
      return "U";
    case 69:
      return "E";
    case 79:
      return "O";
    case 75:
      return "K";
    case 83:
      return "S";
    case 84:
      return "T";
    case 78:
      return "N";
    case 72:
      return "H";
    case 77:
      return "M";
    case 89:
      return "Y";
    case 82:
      return "R";
    case 87:
      return "W";
    case 71:
      return "G";
    case 90:
      return "Z";
    case 74:
      return "J";
    case 68:
      return "D";
    case 66:
      return "B";
    case 86:
      return "V";
    case 80:
      return "P";
    case 70:
      return "F";
    case 81:
      return "Q";
    case 76:
      return "L";
    case 88:
      return "X";
    case 67:
      return "C";
    default:
      return 0;
  }
}

function lCharByKc(kc){
  switch(kc) {
    case 65:
      return "a";
    case 73:
      return "i";
    case 85:
      return "u";
    case 69:
      return "e";
    case 79:
      return "o";
    case 75:
      return "k";
    case 83:
      return "s";
    case 84:
      return "t";
    case 78:
      return "n";
    case 72:
      return "h";
    case 77:
      return "m";
    case 89:
      return "y";
    case 82:
      return "r";
    case 87:
      return "w";
    case 71:
      return "g";
    case 90:
      return "z";
    case 74:
      return "j";
    case 68:
      return "d";
    case 66:
      return "b";
    case 86:
      return "v";
    case 80:
      return "p";
    case 70:
      return "f";
    case 81:
      return "q";
    case 76:
      return "l";
    case 88:
      return "x";
    case 67:
      return "c";
    default:
      return 0;
  }
}
